// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtpjiniuueeualifiqts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0cGppbml1dWVldWFsaWZpcXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTU2NjAsImV4cCI6MjA3MDQ5MTY2MH0.WyQHmsnW_x9_XFujDA5hrcTqiccG6II1Saj4Sez1nNE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});